
// This file has been generated by the GUI designer. Do not modify.
namespace MonoDevelop.AddinAuthoring.Gui
{
	public partial class ExtensionView
	{
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label labelName;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label11;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Button buttonExt;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget MonoDevelop.AddinAuthoring.Gui.ExtensionView
			global::Stetic.BinContainer.Attach (this);
			this.Name = "MonoDevelop.AddinAuthoring.Gui.ExtensionView";
			// Container child MonoDevelop.AddinAuthoring.Gui.ExtensionView.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 12;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelName = new global::Gtk.Label ();
			this.labelName.Name = "labelName";
			this.labelName.Xalign = 0F;
			this.labelName.LabelProp = "<b>Addin Name</b>";
			this.labelName.UseMarkup = true;
			this.vbox3.Add (this.labelName);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.labelName]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Addins.AddinManager.CurrentLocalizer.GetString ("<b><i>Extends:</i></b>");
			this.label11.UseMarkup = true;
			this.vbox5.Add (this.label11);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label11]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonExt = new global::Gtk.Button ();
			this.buttonExt.CanFocus = true;
			this.buttonExt.Name = "buttonExt";
			this.buttonExt.Relief = ((global::Gtk.ReliefStyle)(2));
			this.hbox1.Add (this.buttonExt);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonExt]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox5.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox3.Add (this.vbox5);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox5]));
			w5.Position = 1;
			this.Add (this.vbox3);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
